Repository osmlab/editor-layer-index, pull requests merged in 2018-08, with the labels that each got.

#540 virginia wms layers
  sources/north-america/us/va/VGINBuildingFootprints.geojson
  sources/north-america/us/va/VGINImagery.geojson
  sources/north-america/us/va/VGINPropertyLines.geojson
Labels: waitfor - license / usage permission

#526 add imagery from Geoportal DF
  sources/south-america/br/GeoPortal_DF_2015_imagery.geojson
  sources/south-america/br/GeoPortal_DF_2016_imagery.geojson
  sources/south-america/br/GeoPortal_DF_2017_imagery.geojson
Labels: waitfor - boundary geometry, waitfor - other

#536 Added layer Japan GSI Kiban 2500
  sources/asia/jp/JapanGSIKiban2500.geojson
  sources/asia/jp/JapanGSIStandardMap.geojson
  sources/asia/jp/JapanGSIorthoImagery.geojson
Labels: imagery

#547 Added ortophotos for Lake Balaton, Hungary.
  sources/europe/hu/EUFAR-Balaton-orthophotos.geojson
Labels: waitfor - other

#544 Add vgin sources (new links)
  sources/north-america/us/va/VGINBuildingFootprints.geojson
  sources/north-america/us/va/VGINImagery.geojson
  sources/north-america/us/va/VGINPropertyLines.geojson
Labels: waitfor - other
