Repository osmlab/editor-layer-index, pull requests merged in 2022-08, with the labels that each got.

#1478 added erlangen2020 TrueDOP
  sources/europe/de/Erlangen2020.geojson
Labels: waitfor - boundary geometry, waitfor - other

#1565 MassGIS 2021 Imagery: Specify start & end dates
  sources/north-america/us/ma/MassGIS_2021_Aerial.geojson
Labels: enhancement

#1567 Add Turku ortophoto 2021
  sources/europe/fi/turku-orto-2018-true.geojson
  sources/europe/fi/turku-orto-2021.geojson
  sources/europe/fi/turku-orto.geojson
  sources/europe/fi/turku-topo.geojson
Labels: imagery
